"use strict";

enum codes {
  ACCESS_DENIED = "ACCESS_DENIED",
  BAD_REQUEST = "BAD_REQUEST",
  CONFLICT = "CONFLICT",
  GENERIC = "GENERIC",
  INVALID_REQUEST = "INVALID_REQUEST",
  PAYMENT_REQUIRED = "PAYMENT_REQUIRED",
  PRECONDITION_FAILED = "PRECONDITION_FAILED",
  NOT_AUTHENTICATED = "NOT_AUTHENTICATED",
  NOT_FOUND = "NOT_FOUND",
  TOKEN_EXPIRED = "TOKEN_EXPIRED",
  TOO_MANY_ATTEMPTS = "TOO_MANY_ATTEMPTS",
  UNKNOWN = "UNKNOWN",
}

export default codes;
